# Add this at the very top of your file
env_file:
  - .env

services:
  web:
    image: nginx:latest
    depends_on:
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/usr/share/nginx/html

  database:
    build: ./database
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - database
    environment:
      - FLASK_ENV=development
      - DB_HOST=database
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "5001:5001"
    volumes:
      - ./frontend:/app/frontend
